/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class tRequestMsg : TBase
{
  private string _ActionKey;
  private string _RequestObject;

  public string ActionKey
  {
    get
    {
      return _ActionKey;
    }
    set
    {
      __isset.ActionKey = true;
      this._ActionKey = value;
    }
  }

  public string RequestObject
  {
    get
    {
      return _RequestObject;
    }
    set
    {
      __isset.RequestObject = true;
      this._RequestObject = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool ActionKey;
    public bool RequestObject;
  }

  public tRequestMsg() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              ActionKey = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              RequestObject = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("tRequestMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ActionKey != null && __isset.ActionKey) {
        field.Name = "ActionKey";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ActionKey);
        oprot.WriteFieldEnd();
      }
      if (RequestObject != null && __isset.RequestObject) {
        field.Name = "RequestObject";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(RequestObject);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("tRequestMsg(");
    bool __first = true;
    if (ActionKey != null && __isset.ActionKey) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ActionKey: ");
      __sb.Append(ActionKey);
    }
    if (RequestObject != null && __isset.RequestObject) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("RequestObject: ");
      __sb.Append(RequestObject);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

