/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class tReponseMsg : TBase
{
  private int _ErrorCode;
  private string _ErrorInfo;
  private string _Result;

  public int ErrorCode
  {
    get
    {
      return _ErrorCode;
    }
    set
    {
      __isset.ErrorCode = true;
      this._ErrorCode = value;
    }
  }

  public string ErrorInfo
  {
    get
    {
      return _ErrorInfo;
    }
    set
    {
      __isset.ErrorInfo = true;
      this._ErrorInfo = value;
    }
  }

  public string Result
  {
    get
    {
      return _Result;
    }
    set
    {
      __isset.Result = true;
      this._Result = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool ErrorCode;
    public bool ErrorInfo;
    public bool Result;
  }

  public tReponseMsg() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              ErrorCode = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              ErrorInfo = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              Result = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("tReponseMsg");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.ErrorCode) {
        field.Name = "ErrorCode";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ErrorCode);
        oprot.WriteFieldEnd();
      }
      if (ErrorInfo != null && __isset.ErrorInfo) {
        field.Name = "ErrorInfo";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(ErrorInfo);
        oprot.WriteFieldEnd();
      }
      if (Result != null && __isset.Result) {
        field.Name = "Result";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Result);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("tReponseMsg(");
    bool __first = true;
    if (__isset.ErrorCode) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ErrorCode: ");
      __sb.Append(ErrorCode);
    }
    if (ErrorInfo != null && __isset.ErrorInfo) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("ErrorInfo: ");
      __sb.Append(ErrorInfo);
    }
    if (Result != null && __isset.Result) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Result: ");
      __sb.Append(Result);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

